language: php

php:
    7.0
    7.1

before_script:
  # Pour la version avec composer :
  #- composer global require "squizlabs/php_codesniffer=*"
  #- php security-checker.phar security:check /path/to/composer.lock
  - composer install

script:
    # Ajouter les commandes pour lancer les tests :
    # $ phpcs .
    # Commande pour Security checker = ??
    - docker run --rm -v $PWD:/app phpqa/phpcs .
    - docker run --rm -v $PWD:/app phpsa/security-cheaker security:check
    - phpunit

deploy:
    provider: heroku
    api_key:
        secure: 30e80510-0973-4cb9-bce6-f28be0ce25f8
    app: romainrichard08-opencfp

notifications:
    email:
        recipients:
            - romain.richard.08@hotmail.fr
        on_success: never
        on_failure: always


